name: Product Scraper

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger the workflow on

jobs:
  scrape:
    runs-on: windows-latest #  ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Choose the appropriate Python version

      - name: Install dependencies
        run: pip install -r requirements.txt
        #run: |
        #  pip install -r requirements.txt  # Make sure you have a requirements.txt file with necessary dependencies
          # You might need to install Chrome WebDriver and other necessary tools

      - name: Run scraper
        run: python3 product_scraping/pharmacopeia-and-metrological-institutes-standards.py

      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: scraped-data
          path: product_scraping_output  # Adjust this path to the folder where your CSV files are generated
